language: java

before_install:
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
  - android update sdk --filter platform-tools,android-10 --force --no-ui
