language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" ia32-libs ia32-libs-multiarch libgd2-xpm
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar -zxvf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
  - echo yes | android update sdk --filter platform-tools,android-10,build-tools-19.1.0 --force --no-ui
  - cd foul
