dist: trusty

language: java

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - sudo rm -f /etc/mavenrc
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar -zxvf apache-maven-3.1.1-bin.tar.gz
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
  - export M2_HOME=$PWD/apache-maven-3.1.1
  - export PATH=$M2_HOME/bin:$PATH
  - mvn --version
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get -qq install libncurses5:i386 libstdc++6:i386 zlib1g:i386
  - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -zxvf android-sdk_r24.4.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
  - echo yes | android update sdk --filter platform-tools,android-10,build-tools-25.0.3,addon-google_apis-google-10 --force --no-ui --obsolete
  - git clone https://github.com/mosabua/maven-android-sdk-deployer
  - cd maven-android-sdk-deployer
  - mvn install -P 2.3.3
  - cd ../foul
