language: java

before_install:
  - [ "$(uname -m)" == "x86_64" ] && sudo apt-get update && sudo apt-get install --force-yes ia32-libs
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
  - android update sdk --filter platform-tools,android-10 --force --no-ui
